//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebSeries")]
    public interface IWebSeries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSeries/SearchInventory", ReplyAction="http://tempuri.org/IWebSeries/SearchInventoryResponse")]
        string SearchInventory(string searchString, string SearchType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSeries/SearchInventory", ReplyAction="http://tempuri.org/IWebSeries/SearchInventoryResponse")]
        System.Threading.Tasks.Task<string> SearchInventoryAsync(string searchString, string SearchType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebSeriesChannel : WebApplication2.ServiceReference1.IWebSeries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSeriesClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.IWebSeries>, WebApplication2.ServiceReference1.IWebSeries {
        
        public WebSeriesClient() {
        }
        
        public WebSeriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSeriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSeriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSeriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SearchInventory(string searchString, string SearchType) {
            return base.Channel.SearchInventory(searchString, SearchType);
        }
        
        public System.Threading.Tasks.Task<string> SearchInventoryAsync(string searchString, string SearchType) {
            return base.Channel.SearchInventoryAsync(searchString, SearchType);
        }
    }
}
